### PR TITLE
feat: support ns precision span duration reporting

### PR DESCRIPTION
**Pull request by hughsimpson**
Support finer-grained duration precision following the [0.14.3 release](https://github.com/trace4cats/trace4cats/releases/tag/v0.14.3) of trace4cats-core

### CODE REVIEW

**Comment by hughsimpson** [comment]
@janstenpickle sorry to @ you but not sure how else to progress

**Comment by hughsimpson** [comment]
@janstenpickle any chance you could take a look at this please? Would love some finer-grained resolution on this reporter

**Comment by janstenpickle** [comment]
Hi @hughsimpson really sorry about the delay on this - I'll release this now

**Comment by janstenpickle** [comment]
Released in v0.14.1!

**Pull request merged**
